version: '3'



services:

  sender:
    build: sender
    ports:
      - "8000:8000"
    env_file: ./sender/.env
    depends_on:
      - rest

  rest:
    build: rest
    ports:
      - "8080:8080"
    env_file: ./rest/.env